import type {
  Account,
  Category,
  Dish,
  Invoice,
  MenuTheme,
  Restaurant,
} from "@/lib/types";

export const seedRestaurant: Restaurant = {
  id: "rest-bistro-marche",
  name: "Bistro du Marché",
  slug: "bistro-du-marche",
  tagline: "Seasonal French cooking near the covered market",
  address: "12 Rue des Halles",
  city: "Lyon",
  phone: "+33 4 78 00 00 00",
  email: "contact@bistrodumarche.fr",
  website: "https://bistrodumarche.fr",
  coverImageUrl:
    "https://images.unsplash.com/photo-1414235077428-338989a2e8c0?q=80&w=1600&auto=format&fit=crop",
  currency: "EUR",
  openingHours: [
    { day: "Monday", open: "", close: "", closed: true },
    { day: "Tuesday", open: "12:00", close: "22:30", closed: false },
    { day: "Wednesday", open: "12:00", close: "22:30", closed: false },
    { day: "Thursday", open: "12:00", close: "22:30", closed: false },
    { day: "Friday", open: "12:00", close: "23:00", closed: false },
    { day: "Saturday", open: "12:00", close: "23:00", closed: false },
    { day: "Sunday", open: "12:00", close: "16:00", closed: false },
  ],
  isPublished: true,
  createdAt: "2024-02-14",
};

export const seedTheme: MenuTheme = {
  restaurantId: seedRestaurant.id,
  accentColor: "#8b5cf6",
  background: "paper",
  fontStyle: "classic",
  layout: "cards",
  showPrices: true,
  showAllergens: true,
};

export const seedCategories: Category[] = [
  {
    id: "cat-starters",
    restaurantId: seedRestaurant.id,
    name: "Starters",
    description: "Small plates to open the meal",
    position: 0,
    isVisible: true,
  },
  {
    id: "cat-mains",
    restaurantId: seedRestaurant.id,
    name: "Main Courses",
    description: "Seasonal dishes from the market",
    position: 1,
    isVisible: true,
  },
  {
    id: "cat-desserts",
    restaurantId: seedRestaurant.id,
    name: "Desserts",
    description: "Made in house every morning",
    position: 2,
    isVisible: true,
  },
  {
    id: "cat-drinks",
    restaurantId: seedRestaurant.id,
    name: "Drinks",
    description: "Wine, beer and soft drinks",
    position: 3,
    isVisible: true,
  },
];

export const seedDishes: Dish[] = [
  {
    id: "dish-soupe-oignon",
    categoryId: "cat-starters",
    name: "French Onion Soup",
    description: "Slow-cooked onions, beef broth, toasted bread, melted Comté",
    price: 8.5,
    imageUrl:
      "https://images.unsplash.com/photo-1547592180-85f173990554?q=80&w=800&auto=format&fit=crop",
    allergens: ["gluten", "dairy"],
    tags: ["classic"],
    isAvailable: true,
    isSignature: true,
    position: 0,
  },
  {
    id: "dish-terrine",
    categoryId: "cat-starters",
    name: "Country Terrine",
    description: "Pork terrine, cornichons, toasted sourdough, mustard",
    price: 9,
    imageUrl:
      "https://images.unsplash.com/photo-1541529086526-db283c563270?q=80&w=800&auto=format&fit=crop",
    allergens: ["gluten", "mustard"],
    tags: [],
    isAvailable: true,
    isSignature: false,
    position: 1,
  },
  {
    id: "dish-salade-chevre",
    categoryId: "cat-starters",
    name: "Warm Goat Cheese Salad",
    description: "Mixed leaves, walnuts, honey, grilled goat cheese toasts",
    price: 10.5,
    imageUrl:
      "https://images.unsplash.com/photo-1512621776951-a57141f2eefd?q=80&w=800&auto=format&fit=crop",
    allergens: ["dairy", "nuts", "gluten"],
    tags: ["vegetarian"],
    isAvailable: true,
    isSignature: false,
    position: 2,
  },
  {
    id: "dish-boeuf-bourguignon",
    categoryId: "cat-mains",
    name: "Beef Bourguignon",
    description: "Slow-braised beef in red wine, carrots, pearl onions, mash",
    price: 21,
    imageUrl:
      "https://images.unsplash.com/photo-1600891964092-4316c288032e?q=80&w=800&auto=format&fit=crop",
    allergens: ["sulphites", "dairy"],
    tags: ["signature"],
    isAvailable: true,
    isSignature: true,
    position: 0,
  },
  {
    id: "dish-magret",
    categoryId: "cat-mains",
    name: "Duck Breast, Honey and Thyme",
    description: "Pan-seared duck breast, roasted root vegetables, jus",
    price: 23.5,
    imageUrl:
      "https://images.unsplash.com/photo-1432139555190-58524dae6a55?q=80&w=800&auto=format&fit=crop",
    allergens: [],
    tags: [],
    isAvailable: true,
    isSignature: true,
    position: 1,
  },
  {
    id: "dish-risotto",
    categoryId: "cat-mains",
    name: "Wild Mushroom Risotto",
    description: "Arborio rice, seasonal mushrooms, Parmesan, chives",
    price: 18,
    imageUrl:
      "https://images.unsplash.com/photo-1476124369491-e7addf5db371?q=80&w=800&auto=format&fit=crop",
    allergens: ["dairy"],
    tags: ["vegetarian"],
    isAvailable: true,
    isSignature: false,
    position: 2,
  },
  {
    id: "dish-poisson",
    categoryId: "cat-mains",
    name: "Pan-Seared Sea Bream",
    description: "Market fish, seasonal vegetables, beurre blanc",
    price: 24,
    imageUrl:
      "https://images.unsplash.com/photo-1519708227418-c8fd9a32b7a2?q=80&w=800&auto=format&fit=crop",
    allergens: ["fish", "dairy"],
    tags: [],
    isAvailable: false,
    isSignature: false,
    position: 3,
  },
  {
    id: "dish-creme-brulee",
    categoryId: "cat-desserts",
    name: "Crème Brûlée",
    description: "Vanilla custard, caramelised sugar crust",
    price: 7.5,
    imageUrl:
      "https://images.unsplash.com/photo-1470124182917-cc6e71b22ecc?q=80&w=800&auto=format&fit=crop",
    allergens: ["dairy", "eggs"],
    tags: ["classic"],
    isAvailable: true,
    isSignature: true,
    position: 0,
  },
  {
    id: "dish-tarte-tatin",
    categoryId: "cat-desserts",
    name: "Tarte Tatin",
    description: "Caramelised apple tart, crème fraîche",
    price: 8,
    imageUrl:
      "https://images.unsplash.com/photo-1568571780765-9276ac8b75a2?q=80&w=800&auto=format&fit=crop",
    allergens: ["gluten", "dairy", "eggs"],
    tags: [],
    isAvailable: true,
    isSignature: false,
    position: 1,
  },
  {
    id: "dish-mousse-chocolat",
    categoryId: "cat-desserts",
    name: "Dark Chocolate Mousse",
    description: "70% cocoa mousse, sea salt, shortbread crumble",
    price: 7.5,
    imageUrl:
      "https://images.unsplash.com/photo-1541783245831-57d6fb0926d3?q=80&w=800&auto=format&fit=crop",
    allergens: ["dairy", "eggs", "gluten"],
    tags: ["vegetarian"],
    isAvailable: true,
    isSignature: false,
    position: 2,
  },
  {
    id: "dish-vin-rouge",
    categoryId: "cat-drinks",
    name: "House Red Wine, Glass",
    description: "Côtes du Rhône, medium body",
    price: 6,
    imageUrl:
      "https://images.unsplash.com/photo-1510812431401-41d2bd2722f3?q=80&w=800&auto=format&fit=crop",
    allergens: ["sulphites"],
    tags: [],
    isAvailable: true,
    isSignature: false,
    position: 0,
  },
  {
    id: "dish-eau-petillante",
    categoryId: "cat-drinks",
    name: "Sparkling Water",
    description: "50cl bottle",
    price: 4,
    imageUrl:
      "https://images.unsplash.com/photo-1523362628745-0c100150b504?q=80&w=800&auto=format&fit=crop",
    allergens: [],
    tags: [],
    isAvailable: true,
    isSignature: false,
    position: 1,
  },
];

export const seedAccount: Account = {
  id: "acct-lea-fontaine",
  ownerName: "Léa Fontaine",
  email: "lea@bistrodumarche.fr",
  restaurantId: seedRestaurant.id,
  plan: "standard",
  trialEndsAt: null,
};

export const seedInvoices: Invoice[] = [
  {
    id: "inv-2024-06",
    reference: "MM-2024-0006",
    issuedAt: "2024-06-01",
    amount: 9.99,
    status: "paid",
  },
  {
    id: "inv-2024-05",
    reference: "MM-2024-0005",
    issuedAt: "2024-05-01",
    amount: 9.99,
    status: "paid",
  },
  {
    id: "inv-2024-04",
    reference: "MM-2024-0004",
    issuedAt: "2024-04-01",
    amount: 9.99,
    status: "paid",
  },
];

export const seedScanActivity = [
  { date: "2024-06-10", count: 22 },
  { date: "2024-06-11", count: 31 },
  { date: "2024-06-12", count: 18 },
  { date: "2024-06-13", count: 40 },
  { date: "2024-06-14", count: 52 },
  { date: "2024-06-15", count: 61 },
  { date: "2024-06-16", count: 34 },
];
